#!/bin/sh /etc/rc.common

START=14

run_copyconfig(){
	local enable
	config_get_bool enable $1 enable
	
	if [ $enable ]; then
		local username
		local password
		local domain
		local ifname
		
		config_get username $1 username
		config_get password $1 password
		config_get domain $1 domain
		config_get ifname $1 ifname
		
		echo $username > /var/run/testfile.conf
		echo $username >> /var/run/testfile.conf
		echo $domain >> /var/run/testfile.conf
		echo $ifname >> /var/run/testfile.conf
		
		echo "testfile has started..."
	fi
}

start(){
	config_load login
	config_foreach run_copyconfig login
}
